config/routes.rb
Bootstrap::Application.routes.draw do

  devise_for :members
  resource :home, :controller => "homes"

  get '/about', :to => "homes#about"

  root :to => "homes#index"

  resources :posts do
      resources :says
  end

  resources :lists

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/list.rb
class List < ActiveRecord::Base

  # attr_accessible
  # attr_accessible :title, :category, :body, :published, :attachment, :member_id
  mount_uploader :attachment, AttachmentUploader

  # validation
  validates :title, presence: true, length: { minimum: 5 }
  validates :category, presence: true
  validates :body, presence: true
  validates :published, presence: true


end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attr_accessible
  # attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  # validation
  validates :email, presence: true
  validates :username, presence: true, length: { maximum: 20 }

  # assosiation
  belongs_to :lists

end

app/models/post.rb
class Post < ActiveRecord::Base
  # attr_accessible
  # attr_accessible :title, :text

  # assosiation
  has_many :says, dependent: :destroy

  # validation
  validates :title, presence: true, length: { minimum: 5 }
  validates :text, presence: true

end

app/models/say.rb
class Say < ActiveRecord::Base
  # attr_accessible
  # attr_accessible :commenter, :body

  # validation
  belongs_to :post
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  #  GET - lists_path
  #
  def index
    @lists = List.all
  end

  # GET - new_list_path
  #
  def new
    @list = List.new
  end

  # POST - lists_path
  #
  def create

    @list = List.new(list_params.merge(:member_id => current_member.id))

    if @list.save
      redirect_to @list
    else
      render 'new'
    end
  end

  # GET - edit_list_path(list_id)
  #
  def edit
    @list = List.find(params[:id])
  end

  # PUT - list_path(list_id)
  #
  def update
    @list = List.find(params[:id])

    if @list.update(list_params.merge(:member_id => current_member.id))
      redirect_to @list
    else
      render 'edit'
    end
  end

  # GET - list_path(list_id)
  #
  def show
    @list = List.find(params[:id])
  end

  # DELETE - list_path(list_id)
  #
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path
  end

  private

    # filter list params
    #
    def list_params
      params.require(:list).permit(:title, :category, :body, :published, :attachment)
    end
    # def my_list
    #   @mylist ||= current_member.list.find params[:id]
    # end
end

app/controllers/says_controller.rb
class SaysController < ApplicationController

  # POST - post_says_path
  #
  def create
    @post = Post.find(params[:post_id])
    @say = @post.says.create(params[:say].permit(:commenter, :body))
      redirect_to post_path(@post)
  end

  # DELETE - post_say_path(post_say_id)
  #
  def destroy
    @post = Post.find(params[:post_id])
    @say = @post.says.find(params[:id])
    @say.destroy
    redirect_to post_path(@post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articels_helper.rb
module ArticelsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/ebooks_helper.rb
module EbooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/learnings_helper.rb
module LearningsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/says_helper.rb
module SaysHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Learning RubyonRails.com"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-inverse
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{href: lists_path} Learning RubyonRails
          .container.nav-collapse
            %ul.nav
              %li= link_to "About", about_path
              %li= link_to "List Articel", lists_path
              %li= link_to "Ask", posts_path


    .container

      .row
        .span9
          = bootstrap_flash
          = yield

        .span3
          .well.sidebar-nav
            %h3 Login Section
            %ul.nav.nav-list
              - if member_signed_in?
                %li= link_to "Edit Profile", edit_member_registration_path, :method => :get
                %li= link_to "Sign out", destroy_member_session_path, :method => :delete
              - else
                %li= link_to "Sign In", new_member_session_path, :method => :get
                %li= link_to "Sign up", new_member_registration_path, :method => :get

        .span3
          .well.sidebar-nav
            %h3 Page Member
            %ul.nav.nav-list
              - if member_signed_in?
                %li= link_to "New Articel", new_list_path
                %li= link_to "New Ask", new_post_path

              - else
                %li= link_to "Loream lipsum", '#'
                %li= link_to "Loream lipsum", '#'
                %li= link_to "Loream lipsum", '#'
                %li= link_to "Loream lipsum", '#'
                %li= link_to "Loream lipsum", '#'



  .footer
    %span
      copyright 2014 By Creative
      %a{:href => "https://twitter.com/noer180895", :target => "_blank"} Nurhayati